---
# tasks file for devops_demo
    - name: "Install The Package"

      apt:

        name: nginx

        state: present

      notify: "Stop Service"



    - name: "Update configuration"

      template:

        src: port.j2

        dest: /etc/nginx/sites-enabled/default
     
      notify: "config change"

