---
# tasks file for devops_demo
    - name: "Install The Package"

      apt:

        name: nginx

        state: present



    - name: "Stop The Service"

      service:

        name: nginx

        state: stopped



    - name: "Update configuration"

      template:

        src: port.j2

        dest: /etc/nginx/sites-enabled/default



    - name: "Start The Service"

      service:

        name: nginx

        state: started


