- hosts: web1

  become: yes

  become_user: root

  gather_facts: no

  vars:
 
   server_port: 9091


  tasks:

    - name: "Install The Package"

      apt:

        name: nginx

        state: present

      notify: "Stop service"



    - name: "Update configuration"

      template:

        src: port.j2

        dest: /etc/nginx/sites-enabled/default

      notify: "config change"


  handlers:

    - name: "Stop service"

      service:

        name: nginx

        state: stopped


    - name: "config change"

      service:

        name: nginx

        state: reloaded

