
- hosts: web1

  become: yes

  become_user: root

  gather_facts: no


  tasks:

    - name: "Install The Package"

      apt:

        name: nginx

        state: present



    - name: "Stop The Service"

      service:

        name: nginx

        state: stopped



    - name: "Update configuration"

      template:

        src: port.j2

        dest: /etc/nginx/sites-enabled/default



    - name: "Start The Service"

      service:

        name: nginx

        state: started


